Require Export GR.bicategories.modification.modification.
Require Export GR.bicategories.modification.examples.associativity_inv.
Require Export GR.bicategories.modification.examples.associativity.
Require Export GR.bicategories.modification.examples.composition.
Require Export GR.bicategories.modification.examples.factor_full_sub.
Require Export GR.bicategories.modification.examples.identity.
Require Export GR.bicategories.modification.examples.left_identity_inv.
Require Export GR.bicategories.modification.examples.left_identity.
Require Export GR.bicategories.modification.examples.representable.
Require Export GR.bicategories.modification.examples.representable_id.
Require Export GR.bicategories.modification.examples.representable_comp.
Require Export GR.bicategories.modification.examples.restriction.
Require Export GR.bicategories.modification.examples.right_identity_inv.
Require Export GR.bicategories.modification.examples.right_identity.
Require Export GR.bicategories.modification.examples.whisker_L.
Require Export GR.bicategories.modification.examples.whisker_R.